Repository 08month-team-project/2st-shopping-mall-BE, pull requests merged in 2024-10, with the labels that each got.

#17 🛠Chore: Test yml datasource 추가
  src/test/resources/application.yml
Labels: enhancement

#22 ✨feat: 회원가입 기능 완성
  src/main/java/com/example/shoppingmall/domain/cart/domain/Cart.java
  src/main/java/com/example/shoppingmall/domain/item/domain/Item.java
  src/main/java/com/example/shoppingmall/domain/order/domain/Orders.java
  src/main/java/com/example/shoppingmall/domain/user/api/UserController.java
  src/main/java/com/example/shoppingmall/domain/user/application/UserService.java
  src/main/java/com/example/shoppingmall/domain/user/dao/UserRepository.java
  src/main/java/com/example/shoppingmall/domain/user/domain/Address.java
  src/main/java/com/example/shoppingmall/domain/user/domain/User.java
  src/main/java/com/example/shoppingmall/domain/user/dto/AddressRequest.java
  src/main/java/com/example/shoppingmall/domain/user/dto/SignupRequest.java
  src/main/java/com/example/shoppingmall/domain/user/dto/SignupResponse.java
  src/main/java/com/example/shoppingmall/domain/user/type/Gender.java
  src/main/java/com/example/shoppingmall/global/config/SecurityConfig.java
  src/main/java/com/example/shoppingmall/global/exception/ErrorCode.java
  src/test/java/com/example/shoppingmall/domain/user/api/UserControllerTest.java
  src/test/java/com/example/shoppingmall/domain/user/application/UserServiceTest.java
  src/test/java/com/example/shoppingmall/domain/user/dao/UserRepositoryTest.java
Labels: enhancement

#29 ✨feat: 판매 상품 이미지 등록 기능 완료
  build.gradle
  src/main/java/com/example/shoppingmall/domain/item/api/ItemController.java
  src/main/java/com/example/shoppingmall/domain/item/application/S3Service.java
  src/main/java/com/example/shoppingmall/domain/item/excepction/S3Exception.java
  src/main/java/com/example/shoppingmall/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: enhancement

#33 ✨feat:로그인,로그아웃
  build.gradle
  src/main/java/com/example/shoppingmall/domain/user/api/UserController.java
  src/main/java/com/example/shoppingmall/domain/user/dao/UserRepository.java
  src/main/java/com/example/shoppingmall/domain/user/domain/User.java
  src/main/java/com/example/shoppingmall/domain/user/dto/SigninRequest.java
  src/main/java/com/example/shoppingmall/global/config/RedisConfig.java
  src/main/java/com/example/shoppingmall/global/config/SecurityConfig.java
  src/main/java/com/example/shoppingmall/global/exception/ErrorCode.java
  src/main/java/com/example/shoppingmall/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/shoppingmall/global/security/detail/CustomUserDetailService.java
  src/main/java/com/example/shoppingmall/global/security/detail/CustomUserDetails.java
  src/main/java/com/example/shoppingmall/global/security/dto/UserDetailsDTO.java
  src/main/java/com/example/shoppingmall/global/security/filter/CustomLogoutFilter.java
  src/main/java/com/example/shoppingmall/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/example/shoppingmall/global/security/filter/LoginFilter.java
  src/main/java/com/example/shoppingmall/global/security/util/JwtUtil.java
  src/main/java/com/example/shoppingmall/global/security/util/RedisAuthUtil.java
  src/main/resources/application.yml
Labels: enhancement

#36 ✨feat:회원가입 시 이메일 중복확인
  src/main/java/com/example/shoppingmall/domain/user/api/UserController.java
  src/main/java/com/example/shoppingmall/domain/user/application/UserService.java
  src/main/java/com/example/shoppingmall/domain/user/dto/CheckEmailRequest.java
  src/main/java/com/example/shoppingmall/domain/user/dto/UserResponse.java
  src/main/java/com/example/shoppingmall/global/config/SecurityConfig.java
  src/test/java/com/example/shoppingmall/domain/user/api/UserControllerTest.java
  src/test/java/com/example/shoppingmall/domain/user/application/UserServiceTest.java
Labels: enhancement

#38 🐛Fix(user):로그인,회원가입,로그아웃 수정
  src/main/java/com/example/shoppingmall/TestDataInit_SearchItems.java
  src/main/java/com/example/shoppingmall/domain/user/domain/Address.java
  src/main/java/com/example/shoppingmall/domain/user/dto/AddressRequest.java
  src/main/java/com/example/shoppingmall/domain/user/dto/LoginRequest.java
  src/main/java/com/example/shoppingmall/domain/user/dto/SignupRequest.java
  src/main/java/com/example/shoppingmall/global/config/SecurityConfig.java
  src/main/java/com/example/shoppingmall/global/security/detail/CustomUserDetailService.java
  src/main/java/com/example/shoppingmall/global/security/dto/UserDetailsDTO.java
  src/main/java/com/example/shoppingmall/global/security/filter/CustomLogoutFilter.java
  src/main/java/com/example/shoppingmall/global/security/filter/LoginFilter.java
  src/test/java/com/example/shoppingmall/domain/item/application/ItemServiceTest.java
  src/test/java/com/example/shoppingmall/domain/item/dao/ItemRepositoryTest.java
  src/test/java/com/example/shoppingmall/domain/user/api/UserControllerTest.java
  src/test/java/com/example/shoppingmall/domain/user/application/UserServiceTest.java
  src/test/java/com/example/shoppingmall/domain/user/dao/UserRepositoryTest.java
Labels: enhancement

#48 ✅Feature: 판매 물품 등록 기능 구현
  src/main/java/com/example/shoppingmall/DataInit_CateAndSize.java
  src/main/java/com/example/shoppingmall/TestDataInit_Cart.java
  src/main/java/com/example/shoppingmall/domain/item/api/ItemController.java
  src/main/java/com/example/shoppingmall/domain/item/application/ItemService.java
  src/main/java/com/example/shoppingmall/domain/item/application/S3Service.java
  src/main/java/com/example/shoppingmall/domain/item/dao/CategoryRepository.java
  src/main/java/com/example/shoppingmall/domain/item/dao/ClothingSizeRepository.java
  src/main/java/com/example/shoppingmall/domain/item/domain/Category.java
  src/main/java/com/example/shoppingmall/domain/item/domain/CategoryItem.java
  src/main/java/com/example/shoppingmall/domain/item/domain/Item.java
  src/main/java/com/example/shoppingmall/domain/item/domain/ItemImage.java
  src/main/java/com/example/shoppingmall/domain/item/domain/ItemStock.java
  src/main/java/com/example/shoppingmall/domain/item/dto/CategoryList.java
  src/main/java/com/example/shoppingmall/domain/item/dto/CategoryResponse.java
  src/main/java/com/example/shoppingmall/domain/item/dto/RegisterRequest.java
  src/main/java/com/example/shoppingmall/domain/item/dto/SellerResponse.java
  src/main/java/com/example/shoppingmall/domain/item/dto/SizeItem.java
  src/main/java/com/example/shoppingmall/domain/item/dto/SizeResponse.java
  src/main/java/com/example/shoppingmall/domain/user/dto/SignupRequest.java
  src/main/java/com/example/shoppingmall/global/annotation/BadWordFilter.java
  src/main/java/com/example/shoppingmall/global/annotation/CensorService.java
  src/main/java/com/example/shoppingmall/global/annotation/CensorValidator.java
  src/main/java/com/example/shoppingmall/global/config/SecurityConfig.java
  src/main/java/com/example/shoppingmall/global/exception/ErrorCode.java
  src/main/java/com/example/shoppingmall/global/exception/GlobalExceptionHandler.java
  src/test/java/com/example/shoppingmall/domain/item/application/ItemServiceRegisterTest.java
Labels: enhancement

#41 ✨Feat: 회원탈퇴 기능 구현
  src/main/java/com/example/shoppingmall/domain/user/api/UserController.java
  src/main/java/com/example/shoppingmall/domain/user/application/UserService.java
  src/main/java/com/example/shoppingmall/domain/user/domain/User.java
  src/main/java/com/example/shoppingmall/global/exception/ErrorCode.java
Labels: enhancement

#50 🛠Chore: AWS EC2 S3, React 연동 테스트
  src/main/java/com/example/shoppingmall/global/config/SecurityConfig.java
  src/main/java/com/example/shoppingmall/global/config/WebConfig.java
  src/main/resources/application-prod.yml
Labels: enhancement

#49 🛠Chore:로그인 후 응답 데이터 수정
  src/main/java/com/example/shoppingmall/global/security/detail/CustomUserDetails.java
  src/main/java/com/example/shoppingmall/global/security/dto/UserDetailsDTO.java
  src/main/java/com/example/shoppingmall/global/security/filter/LoginFilter.java
Labels: wontfix

#53 ✨Feat: 판매자로 변경 기능 추가
  src/main/java/com/example/shoppingmall/domain/user/api/UserController.java
  src/main/java/com/example/shoppingmall/domain/user/application/UserService.java
  src/main/java/com/example/shoppingmall/domain/user/domain/User.java
  src/main/java/com/example/shoppingmall/global/exception/ErrorCode.java
Labels: enhancement

#57 Feature item find
  src/main/java/com/example/shoppingmall/DataInit_CateAndSize.java
  src/main/java/com/example/shoppingmall/domain/item/api/ItemController.java
  src/main/java/com/example/shoppingmall/domain/item/application/ItemService.java
  src/main/java/com/example/shoppingmall/domain/item/dao/ItemRepository.java
  src/main/java/com/example/shoppingmall/domain/item/dao/ItemRepositorySellerCustom.java
  src/main/java/com/example/shoppingmall/domain/item/dao/ItemRepositorySellerCustomImpl.java
  src/main/java/com/example/shoppingmall/domain/item/domain/Item.java
  src/main/java/com/example/shoppingmall/domain/item/domain/ItemStock.java
  src/main/java/com/example/shoppingmall/domain/item/dto/RegisterRequest.java
  src/main/java/com/example/shoppingmall/domain/item/dto/SellerItemResponse.java
  src/main/java/com/example/shoppingmall/domain/item/dto/UpdateItemRequest.java
  src/main/java/com/example/shoppingmall/global/config/SecurityConfig.java
  src/main/java/com/example/shoppingmall/global/exception/ErrorCode.java
  src/main/resources/static/img1.jpg
  src/main/resources/static/img2.jpg
  src/main/resources/static/img3.png
Labels: enhancement

#64 :sparkles: Feat(seller): 버그 및 수정 사항 해결
  src/main/java/com/example/shoppingmall/domain/item/application/S3Service.java
  src/main/java/com/example/shoppingmall/domain/item/dao/ItemRepositorySellerCustomImpl.java
  src/main/java/com/example/shoppingmall/domain/item/domain/ItemStock.java
  src/main/java/com/example/shoppingmall/domain/item/dto/SellerItemResponse.java
Labels: enhancement

#71 Update README.md
  README.md
Labels: documentation
